#!/usr/bin/env python3.6
# -*- coding: UTF-8 -*-


# Before this will work, make sure to run:
#
#   ./generate-secret.py example
import sys

sys.path.append("..")

from libredeploy import redeploy

redeploy(
    app_name=__file__,
    # This is the directory where your app lives
    directory="/opt",
    # This is the shell script of how to do the redeploy.
    # Normally, this is a git pull, followed by someway to tell the
    # server to reload the app.
    script="false",
    # This allows you to override environment variables, if necessary.
    env={
        "LANG": "en-CA.UTF-8"
    }
)
