#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from libredeploy import redeploy

redeploy(app_name=__file__,
         directory='/Users/eddieantonio/Projects/itwewina/neahtta',
         script='false && git pull && touch itwewina.wsgi')
